apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: deploy-proj-1d1cb20caf47
  labels:
    app: grafana
data:
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus.deploy-proj-1d1cb20caf47:9090
        isDefault: true
