apiVersion: v1
kind: Service
metadata:
  name: eval-fastapi-min
  labels:
    app.kubernetes.io/name: eval-fastapi-min
    app.kubernetes.io/instance: eval-fastapi-min
    app.kubernetes.io/part-of: eval-fastapi-min
spec:
  type: NodePort
  selector:
    app: eval-fastapi-min
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
